// Seslendirilmiş sözler: söz → sesler/<dosya>.mp3 (araclar/seslendir.py üretir).
// Burada olmayan sözleri tarayıcının Türkçe sesi okur.
const SES_DOSYALARI = {
 "a": "harf-a",
 "e": "harf-e",
 "i": "harf-i",
 "an": "hece-an",
 "na": "hece-na",
 "at": "hece-at",
 "ta": "hece-ta",
 "al": "hece-al",
 "la": "hece-la",
 "en": "hece-en",
 "ne": "hece-ne",
 "et": "hece-et",
 "te": "hece-te",
 "el": "hece-el",
 "le": "hece-le",
 "in": "hece-in",
 "ni": "hece-ni",
 "it": "hece-it",
 "ti": "hece-ti",
 "il": "hece-il",
 "li": "hece-li",
 "lan": "hece-lan",
 "nat": "hece-nat",
 "ten": "hece-ten",
 "let": "hece-let",
 "tel": "hece-tel",
 "arı": "kelime-ari",
 "nar": "kelime-nar",
 "eşek": "kelime-esek",
 "tilki": "kelime-tilki",
 "inek": "kelime-inek",
 "leylek": "kelime-leylek",
 "anne": "kelime-anne",
 "nane": "kelime-nane",
 "lale": "kelime-lale",
 "nine": "kelime-nine",
 "tane": "kelime-tane",
 "elle": "kelime-elle",
 "elli": "kelime-elli",
 "ana": "kelime-ana",
 "ata": "kelime-ata",
 "ilan": "kelime-ilan",
 "inat": "kelime-inat",
 "anten": "kelime-anten",
 "atlet": "kelime-atlet",
 "telli": "kelime-telli",
 "anla": "kelime-anla",
 "ilet": "kelime-ilet",
 "Yelkenli hazır! Aferin!": "soz-yelkenli-hazir-aferin",
 "Büyük bir fırtına çıktı!": "soz-buyuk-bir-firtina-cikti",
 "Salın kırıldı...": "soz-salin-kirildi",
 "Bir adaya düştün.": "soz-bir-adaya-dustun",
 "Yelkenliyi tamamla, adadan kurtul!": "soz-yelkenliyi-tamamla-adadan-kurtul",
 "Haydi, yola çıkalım!": "soz-haydi-yola-cikalim",
 "Hoşça kal, ilk ada!": "soz-hosca-kal-ilk-ada",
 "2. ada seni bekliyor!": "soz-2-ada-seni-bekliyor",
 "Damla Yakalama": "oyun-damla-yakalama",
 "Harf Balonları": "oyun-harf-balonlari",
 "Harfi Yaz": "oyun-harfi-yaz",
 "Resimden Sesi Bul": "oyun-resimden-sesi-bul",
 "Hafıza Kartları": "oyun-hafiza-kartlari",
 "Hece Köprüsü": "oyun-hece-koprusu",
 "Heceyi Bul": "oyun-heceyi-bul",
 "Labirent": "oyun-labirent",
 "Şeker Patlatma": "oyun-seker-patlatma",
 "Kayak": "oyun-kayak",
 "Elektrik Devresi": "oyun-elektrik-devresi",
 "Duvardan Geçme": "oyun-duvardan-gecme",
 "Hece Müziği": "oyun-hece-muzigi",
 "Scrabble": "oyun-scrabble",
 "Ördek Vurma": "oyun-ordek-vurma",
 "Kazma": "oyun-kazma",
 "Altın Madencisi": "oyun-altin-madencisi",
 "Kazı Kazan": "oyun-kazi-kazan",
 "Tombala": "oyun-tombala",
 "Arabayı Ulaştır": "oyun-arabayi-ulastir",
 "Yakala ve Yaz": "oyun-yakala-ve-yaz",
 "Kırık Cam": "oyun-kirik-cam",
 "Bombayı Kurtar": "oyun-bombayi-kurtar",
 "Yılan": "oyun-yilan",
 "Canavarı Besle": "oyun-canavari-besle",
 "Harf Kesme": "oyun-harf-kesme",
 "Hece Kulesi": "oyun-hece-kulesi",
 "Birleştir Büyüt": "oyun-birlestir-buyut",
 "Harfle Boya": "oyun-harfle-boya",
 "Harf Fırtınası": "oyun-harf-firtinasi"
};
