// Seslendirilmiş sözler: söz → sesler/<dosya>.mp3. Öğretmenin kendi sesi (kayit.html), peri efektiyle
// (heceler ve harf seslerinde daha az yankı); fırtına ve ada sözlerinde arkada rüzgâr / dalga.
// Burada olmayan sözleri tarayıcının Türkçe sesi okur.
const SES_DOSYALARI = {
 "a": "harf-a",
 "n": "harf-n",
 "nnn": "harf-n",
 "e": "harf-e",
 "t": "harf-t",
 "i": "harf-i",
 "l": "harf-l",
 "lll": "harf-l",
 "an": "hece-an",
 "na": "hece-na",
 "at": "hece-at",
 "ta": "hece-ta",
 "al": "hece-al",
 "la": "hece-la",
 "en": "hece-en",
 "ne": "hece-ne",
 "et": "hece-et",
 "te": "hece-te",
 "el": "hece-el",
 "le": "hece-le",
 "in": "hece-in",
 "ni": "hece-ni",
 "it": "hece-it",
 "ti": "hece-ti",
 "il": "hece-il",
 "li": "hece-li",
 "nan": "hece-nan",
 "nat": "hece-nat",
 "nal": "hece-nal",
 "tan": "hece-tan",
 "tat": "hece-tat",
 "tal": "hece-tal",
 "lan": "hece-lan",
 "lat": "hece-lat",
 "lal": "hece-lal",
 "nen": "hece-nen",
 "net": "hece-net",
 "nel": "hece-nel",
 "ten": "hece-ten",
 "tet": "hece-tet",
 "tel": "hece-tel",
 "len": "hece-len",
 "let": "hece-let",
 "lel": "hece-lel",
 "nin": "hece-nin",
 "nit": "hece-nit",
 "nil": "hece-nil",
 "tin": "hece-tin",
 "tit": "hece-tit",
 "til": "hece-til",
 "lin": "hece-lin",
 "lit": "hece-lit",
 "lil": "hece-lil",
 "arı": "kelime-ari",
 "nar": "kelime-nar",
 "eşek": "kelime-esek",
 "tilki": "kelime-tilki",
 "inek": "kelime-inek",
 "leylek": "kelime-leylek",
 "anne": "kelime-anne",
 "nane": "kelime-nane",
 "lale": "kelime-lale",
 "nine": "kelime-nine",
 "tane": "kelime-tane",
 "elle": "kelime-elle",
 "elli": "kelime-elli",
 "ana": "kelime-ana",
 "ata": "kelime-ata",
 "ilan": "kelime-ilan",
 "inat": "kelime-inat",
 "anten": "kelime-anten",
 "atlet": "kelime-atlet",
 "telli": "kelime-telli",
 "anla": "kelime-anla",
 "ilet": "kelime-ilet",
 "taneli": "kelime-taneli",
 "naneli": "kelime-naneli",
 "laleli": "kelime-laleli",
 "antenli": "kelime-antenli",
 "inatla": "kelime-inatla",
 "anlatan": "kelime-anlatan",
 "anteni": "kelime-anteni",
 "atletli": "kelime-atletli",
 "ağaç": "kelime-agac",
 "altın": "kelime-altin",
 "anahtar": "kelime-anahtar",
 "araba": "kelime-araba",
 "armut": "kelime-armut",
 "aslan": "kelime-aslan",
 "ateş": "kelime-ates",
 "ay": "kelime-ay",
 "ayak": "kelime-ayak",
 "ayakkabı": "kelime-ayakkabi",
 "ayı": "kelime-ayi",
 "ayna": "kelime-ayna",
 "bal": "kelime-bal",
 "balık": "kelime-balik",
 "balon": "kelime-balon",
 "bardak": "kelime-bardak",
 "bebek": "kelime-bebek",
 "biber": "kelime-biber",
 "bilezik": "kelime-bilezik",
 "bilye": "kelime-bilye",
 "bulut": "kelime-bulut",
 "ceket": "kelime-ceket",
 "ceviz": "kelime-ceviz",
 "civciv": "kelime-civciv",
 "çanta": "kelime-canta",
 "çatal": "kelime-catal",
 "çiçek": "kelime-cicek",
 "çorba": "kelime-corba",
 "deve": "kelime-deve",
 "diş": "kelime-dis",
 "dondurma": "kelime-dondurma",
 "ekmek": "kelime-ekmek",
 "elbise": "kelime-elbise",
 "eldiven": "kelime-eldiven",
 "elma": "kelime-elma",
 "erik": "kelime-erik",
 "etek": "kelime-etek",
 "ev": "kelime-ev",
 "fare": "kelime-fare",
 "fener": "kelime-fener",
 "fındık": "kelime-findik",
 "fırça": "kelime-firca",
 "fıstık": "kelime-fistik",
 "fil": "kelime-fil",
 "fincan": "kelime-fincan",
 "gemi": "kelime-gemi",
 "gül": "kelime-gul",
 "halı": "kelime-hali",
 "havuç": "kelime-havuc",
 "hindi": "kelime-hindi",
 "iguana": "kelime-iguana",
 "iğne": "kelime-igne",
 "iki": "kelime-iki",
 "inci": "kelime-inci",
 "incir": "kelime-incir",
 "ip": "kelime-ip",
 "iplik": "kelime-iplik",
 "kale": "kelime-kale",
 "kalem": "kelime-kalem",
 "kanguru": "kelime-kanguru",
 "kapı": "kelime-kapi",
 "kartal": "kelime-kartal",
 "kaşık": "kelime-kasik",
 "kazan": "kelime-kazan",
 "keçi": "kelime-keci",
 "kedi": "kelime-kedi",
 "kelebek": "kelime-kelebek",
 "kemik": "kelime-kemik",
 "kepçe": "kelime-kepce",
 "kibrit": "kelime-kibrit",
 "kilit": "kelime-kilit",
 "kiraz": "kelime-kiraz",
 "kirpi": "kelime-kirpi",
 "kitap": "kelime-kitap",
 "kova": "kelime-kova",
 "koyun": "kelime-koyun",
 "kulak": "kelime-kulak",
 "kumbara": "kelime-kumbara",
 "kurbağa": "kelime-kurbaga",
 "kutu": "kelime-kutu",
 "küpe": "kelime-kupe",
 "lahana": "kelime-lahana",
 "lahmacun": "kelime-lahmacun",
 "lama": "kelime-lama",
 "lamba": "kelime-lamba",
 "leğen": "kelime-legen",
 "limon": "kelime-limon",
 "lokum": "kelime-lokum",
 "masa": "kelime-masa",
 "nehir": "kelime-nehir",
 "nergis": "kelime-nergis",
 "nohut": "kelime-nohut",
 "nota": "kelime-nota",
 "otobüs": "kelime-otobus",
 "ördek": "kelime-ordek",
 "panda": "kelime-panda",
 "patates": "kelime-patates",
 "pil": "kelime-pil",
 "pizza": "kelime-pizza",
 "sepet": "kelime-sepet",
 "silgi": "kelime-silgi",
 "sincap": "kelime-sincap",
 "süt": "kelime-sut",
 "şemsiye": "kelime-semsiye",
 "tabak": "kelime-tabak",
 "tarak": "kelime-tarak",
 "tavşan": "kelime-tavsan",
 "tavuk": "kelime-tavuk",
 "tencere": "kelime-tencere",
 "terlik": "kelime-terlik",
 "testere": "kelime-testere",
 "timsah": "kelime-timsah",
 "top": "kelime-top",
 "tren": "kelime-tren",
 "yaprak": "kelime-yaprak",
 "yatak": "kelime-yatak",
 "yengeç": "kelime-yengec",
 "yorgan": "kelime-yorgan",
 "zeytin": "kelime-zeytin",
 "zil": "kelime-zil",
 "Başında a olan resimleri bul!": "soz-basinda-a-olan-resimleri-bul",
 "Sonunda a olan resimleri bul!": "soz-sonunda-a-olan-resimleri-bul",
 "Ortasında a olan resimleri bul!": "soz-ortasinda-a-olan-resimleri-bul",
 "Başında bu harf olan resimleri bul!": "soz-basinda-bu-harf-olan-resimleri-bul",
 "Sonunda bu harf olan resimleri bul!": "soz-sonunda-bu-harf-olan-resimleri-bul",
 "Ortasında bu harf olan resimleri bul!": "soz-ortasinda-bu-harf-olan-resimleri-bul",
 "Başında e olan resimleri bul!": "soz-basinda-e-olan-resimleri-bul",
 "Sonunda e olan resimleri bul!": "soz-sonunda-e-olan-resimleri-bul",
 "Ortasında e olan resimleri bul!": "soz-ortasinda-e-olan-resimleri-bul",
 "Başında i olan resimleri bul!": "soz-basinda-i-olan-resimleri-bul",
 "Sonunda i olan resimleri bul!": "soz-sonunda-i-olan-resimleri-bul",
 "Ortasında i olan resimleri bul!": "soz-ortasinda-i-olan-resimleri-bul",
 "Büyük bir fırtına çıktı!": "soz-buyuk-bir-firtina-cikti",
 "Salın kırıldı...": "soz-salin-kirildi",
 "Bir adaya düştün.": "soz-bir-adaya-dustun",
 "Yelkenliyi tamamla, adadan kurtul!": "soz-yelkenliyi-tamamla-adadan-kurtul",
 "Yelkenli hazır! Aferin!": "soz-yelkenli-hazir-aferin",
 "Haydi, yola çıkalım!": "soz-haydi-yola-cikalim",
 "Hoşça kal, ilk ada!": "soz-hosca-kal-ilk-ada",
 "2. ada seni bekliyor!": "soz-2-ada-seni-bekliyor",
 "Damla Yakalama": "oyun-damla-yakala",
 "Harf Balonları": "oyun-harf-balonlari",
 "Harfi Yaz": "oyun-harfi-yaz",
 "Resimden Sesi Bul": "oyun-resimden-ses",
 "Hafıza Kartları": "oyun-hafiza-kartlari",
 "Hece Köprüsü": "oyun-hece-koprusu",
 "Heceyi Bul": "oyun-heceyi-bul",
 "Labirent": "oyun-labirent",
 "Şeker Patlatma": "oyun-seker-patlatma",
 "Kayak": "oyun-kayak",
 "Elektrik Devresi": "oyun-elektrik-devresi",
 "Duvardan Geçme": "oyun-duvardan-gecme",
 "Hece Müziği": "oyun-hece-muzigi",
 "Scrabble": "oyun-scrabble",
 "Ördek Vurma": "oyun-ordek-vurma",
 "Kazma": "oyun-kazma",
 "Altın Madencisi": "oyun-altin-madencisi",
 "Kazı Kazan": "oyun-kazi-kazan",
 "Tombala": "oyun-tombala",
 "Arabayı Ulaştır": "oyun-arabayi-ulastir",
 "Yakala ve Yaz": "oyun-yakala-yaz",
 "Kırık Cam": "oyun-kirik-cam",
 "Bombayı Kurtar": "oyun-bombayi-kurtar",
 "Yılan": "oyun-yilan",
 "Canavarı Besle": "oyun-canavari-besle",
 "Harf Kesme": "oyun-harf-kesme",
 "Hece Kulesi": "oyun-hece-kulesi",
 "Birleştir Büyüt": "oyun-birlestir-buyut",
 "Harfle Boya": "oyun-harfle-boya",
 "Harf Fırtınası": "oyun-harf-firtinasi",
 "Merhaba! Ben bu adanın perisiyim.": "soz-merhaba-ben-bu-adanin-perisiyim",
 "Adadan kurtulman için sana yardım edeceğim.": "soz-adadan-kurtulman-icin-sana-yardim-edecegim",
 "Adadan kurtulmak için yelkenlinin 6 parçasını bulmalısın.": "soz-adadan-kurtulmak-icin-yelkenlinin-6-parcasini-bulmalisin",
 "Önce harf tohumlarını bul. Tohumlar sandıklarda saklı.": "soz-once-harf-tohumlarini-bul-tohumlar-sandiklarda-sakli",
 "Işıklar sandığın yönünü gösterir. Işığa doğru yürü! Yaklaştıkça ışık çoğalır, bip hızlanır.": "soz-isiklar-sandigin-yonunu-gosterir-isiga-dogru-yuru-yaklastikca-isik-cogalir-bip-hizlanir",
 "Tohumu tarlana ek.": "soz-tohumu-tarlana-ek",
 "Suyu kıyıdaki su tesisinden alırsın. Harfinin variline dokun, oyun oyna, damla kazan.": "soz-suyu-kiyidaki-su-tesisinden-alirsin-harfinin-variline-dokun-oyun-oyna-damla-kazan",
 "Damlalar şişene dolar. Şişeyi tohuma sürükle, sula. Tohum fasulye sırığı olsun.": "soz-damlalar-sisene-dolar-siseyi-tohuma-surukle-sula-tohum-fasulye-sirigi-olsun",
 "Sırıktan bulutlara tırman, yelkenli parçasını al!": "soz-siriktan-bulutlara-tirman-yelkenli-parcasini-al",
 "Görev düğmesine basıp görevlerini takip edebilirsin.": "soz-gorev-dugmesine-basip-gorevlerini-takip-edebilirsin",
 "Aferin! Şimdi bütün tohumları bul, sula ve fasulye sırığına dönüştür. Sırığa tırman, bulutların üstünde tekrar buluşalım!": "soz-aferin-simdi-butun-tohumlari-bul-sula-ve-fasulye-sirigina-donustur-siriga-tirman-bulutlarin-ustunde-tekrar-bulusalim",
 "Harika! Şimdi sırığa dokun, aşağı in.": "soz-harika-simdi-siriga-dokun-asagi-in",
 "Işığa doğru yürü, sandığı bul! Gitmek istediğin yere dokun.": "soz-isiga-dogru-yuru-sandigi-bul-gitmek-istedigin-yere-dokun",
 "Sandık çıktı! Sandığa dokun.": "soz-sandik-cikti-sandiga-dokun",
 "Tohum çantana girdi! Tarlaya git, sonra çantana dokun.": "soz-tohum-cantana-girdi-tarlaya-git-sonra-cantana-dokun",
 "Önce çantayı kapat ve tarlaya git.": "soz-once-cantayi-kapat-ve-tarlaya-git",
 "Tohumu tarladaki boş kareye sürükle.": "soz-tohumu-tarladaki-bos-kareye-surukle",
 "Şişeyi tarladaki tohuma sürükle.": "soz-siseyi-tarladaki-tohuma-surukle",
 "Parçayı yelkenliye sürükle. Yelkenli kıyıda, su tesisinin yanında.": "soz-parcayi-yelkenliye-surukle-yelkenli-kiyida-su-tesisinin-yaninda",
 "Tohum su istiyor! Kıyıdaki su tesisine git, tesise dokun.": "soz-tohum-su-istiyor-kiyidaki-su-tesisine-git-tesise-dokun",
 "Harfinin variline dokun. Oyunu oyna, damla kazan!": "soz-harfinin-variline-dokun-oyunu-oyna-damla-kazan",
 "Damla şişene aktı! Tarlaya git, çantandaki şişeyle tohumu sula.": "soz-damla-sisene-akti-tarlaya-git-cantandaki-siseyle-tohumu-sula",
 "Fasulye sırığı oldu! Sırığın dibine git, Çık düğmesine bas.": "soz-fasulye-sirigi-oldu-sirigin-dibine-git-cik-dugmesine-bas",
 "Parçayı aldın! Yelkenliye götür. Görev listesindeki yelkenliye dokun.": "soz-parcayi-aldin-yelkenliye-gotur-gorev-listesindeki-yelkenliye-dokun",
 "Söylenen harfin damlalarına dokun!": "soz-soylenen-harfin-damlalarina-dokun",
 "Söylenen harfin balonlarını patlat!": "soz-soylenen-harfin-balonlarini-patlat",
 "Kola bas, malzemeleri harfin üstüne diz!": "soz-kola-bas-malzemeleri-harfin-ustune-diz",
 "Resmi harfin yolunda götür, harfi yaz!": "soz-resmi-harfin-yolunda-gotur-harfi-yaz",
 "Harfin yerine bak, doğru resimlere dokun!": "soz-harfin-yerine-bak-dogru-resimlere-dokun",
 "Kartları ikişer aç, eşlerini bul!": "soz-kartlari-ikiser-ac-eslerini-bul",
 "Söylenen heceyi taşlarla yaz, köprüyü kur!": "soz-soylenen-heceyi-taslarla-yaz-kopruyu-kur",
 "Söylenen hecenin yazılı olduğu balığa dokun!": "soz-soylenen-hecenin-yazili-oldugu-baliga-dokun",
 "Söylenen hecenin kapısını seç, çıkışı bul!": "soz-soylenen-hecenin-kapisini-sec-cikisi-bul",
 "Söylenen hecenin harflerini sırayla seç, şekerleri patlat!": "soz-soylenen-hecenin-harflerini-sirayla-sec-sekerleri-patlat",
 "Sağa sola dokun. Söylenen harfin toplarını topla, kayalardan kaç!": "soz-saga-sola-dokun-soylenen-harfin-toplarini-topla-kayalardan-kac",
 "Söyleneni bul. Parçaları soldan sağa kabloyla bağla!": "soz-soyleneni-bul-parcalari-soldan-saga-kabloyla-bagla",
 "Söylenen harfin kapısına geç! Dokun ya da sürükle.": "soz-soylenen-harfin-kapisina-gec-dokun-ya-da-surukle",
 "Melodiyi dinle, tuşlara aynı sırayla bas!": "soz-melodiyi-dinle-tuslara-ayni-sirayla-bas",
 "Söylenen hecenin notası çizgiye gelince dokun!": "soz-soylenen-hecenin-notasi-cizgiye-gelince-dokun",
 "Söylenen kelimeyi harf taşlarıyla yaz!": "soz-soylenen-kelimeyi-harf-taslariyla-yaz",
 "Söylenen harfli ördekleri vur!": "soz-soylenen-harfli-ordekleri-vur",
 "Kazarak ilerle, söylenen harfin taşlarını topla!": "soz-kazarak-ilerle-soylenen-harfin-taslarini-topla",
 "Kanca doğru harfe bakınca dokun, altını çek!": "soz-kanca-dogru-harfe-bakinca-dokun-altini-cek",
 "Gümüşü parmağınla kazı. Resim çıkınca harfin yerini seç!": "soz-gumusu-parmaginla-kazi-resim-cikinca-harfin-yerini-sec",
 "Torbadan çıkan harfle başlayan resme pul koy!": "soz-torbadan-cikan-harfle-baslayan-resme-pul-koy",
 "Çıkan harfle başlayan resme pul koy. Kartında yoksa, kartımda yok düğmesine bas!": "soz-cikan-harfle-baslayan-resme-pul-koy-kartinda-yoksa-kartimda-yok-dugmesine-bas",
 "Parmağınla yol çiz. Araba doğru harflerden geçip bayrağa ulaşsın!": "soz-parmaginla-yol-ciz-araba-dogru-harflerden-gecip-bayraga-ulassin",
 "Söylenen kelimenin harflerini sırayla ağla yakala!": "soz-soylenen-kelimenin-harflerini-sirayla-agla-yakala",
 "Torbadan çıkanı kartında bul, üstüne pul koy!": "soz-torbadan-cikani-kartinda-bul-ustune-pul-koy",
 "Torbadan çıkanı kartında bul. Kartında yoksa, kartımda yok düğmesine bas!": "soz-torbadan-cikani-kartinda-bul-kartinda-yoksa-kartimda-yok-dugmesine-bas",
 "Camdaki harfleri bul, camı kır!": "soz-camdaki-harfleri-bul-cami-kir",
 "Söylenen harfin kablosunu kes, bombayı kurtar!": "soz-soylenen-harfin-kablosunu-kes-bombayi-kurtar",
 "Yılanı yönlendir, söylenen harfi ye!": "soz-yilani-yonlendir-soylenen-harfi-ye",
 "Canavarın istediği harfli meyveyi ağzına götür!": "soz-canavarin-istedigi-harfli-meyveyi-agzina-gotur",
 "Parmağını kaydır, söylenen harfli meyveleri kes!": "soz-parmagini-kaydir-soylenen-harfli-meyveleri-kes",
 "Söylenen heceyi seç, sonra bloğu kulenin üstüne bırak!": "soz-soylenen-heceyi-sec-sonra-blogu-kulenin-ustune-birak",
 "Taşları kaydır, harfleri yan yana getirip hece kur!": "soz-taslari-kaydir-harfleri-yan-yana-getirip-hece-kur",
 "Söylenen harfin olduğu yerlere dokun, resmi boya!": "soz-soylenen-harfin-oldugu-yerlere-dokun-resmi-boya",
 "Hızlı ol! Her görevde söyleneni yap!": "soz-hizli-ol-her-gorevde-soyleneni-yap",
 "Şimdi söylenen hecenin harflerini sırayla bul!": "soz-simdi-soylenen-hecenin-harflerini-sirayla-bul",
 "Şimdi söylenen kelimenin hecelerini sırayla bul!": "soz-simdi-soylenen-kelimenin-hecelerini-sirayla-bul",
 "Yine buluştuk! a tabelasına yürü, parçanı al.": "soz-yine-bulustuk-a-tabelasina-yuru-parcani-al",
 "Yine buluştuk! n tabelasına yürü, parçanı al.": "soz-yine-bulustuk-n-tabelasina-yuru-parcani-al",
 "Yine buluştuk! e tabelasına yürü, parçanı al.": "soz-yine-bulustuk-e-tabelasina-yuru-parcani-al",
 "Yine buluştuk! t tabelasına yürü, parçanı al.": "soz-yine-bulustuk-t-tabelasina-yuru-parcani-al",
 "Yine buluştuk! i tabelasına yürü, parçanı al.": "soz-yine-bulustuk-i-tabelasina-yuru-parcani-al",
 "Yine buluştuk! l tabelasına yürü, parçanı al.": "soz-yine-bulustuk-l-tabelasina-yuru-parcani-al"
};
